const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nunsseom', {
  // 위젯
  onTick: (cb) => ipcRenderer.on('tick', (_e, data) => cb(data)),
  onScrim: (cb) => ipcRenderer.on('scrim', (_e, v) => cb(v)),
  onRadius: (cb) => ipcRenderer.on('radius', (_e, v) => cb(v)),
  togglePause: () => ipcRenderer.send('widget:toggle-pause'),
  breakNow: (id) => ipcRenderer.send('widget:break-now', id),
  openSettings: (tab) => ipcRenderer.send('widget:open-settings', tab),
  onSettingsTab: (cb) => ipcRenderer.on('settings:tab', (_e, t) => cb(t)),
  openStats: (id) => ipcRenderer.send('widget:open-stats', id),
  hideWidget: () => ipcRenderer.send('widget:hide'),

  // 기록 창
  statsData: (typeId) => ipcRenderer.invoke('stats:data', typeId),
  statsSetWeeks: (weeks) => ipcRenderer.send('stats:set-weeks', weeks),
  statsBreakNow: (id) => ipcRenderer.send('stats:break-now', id),
  statsClose: () => ipcRenderer.send('stats:close'),
  onStatsChanged: (cb) => ipcRenderer.on('stats:changed', () => cb()),
  onStatsFocus: (cb) => ipcRenderer.on('stats:focus', (_e, id) => cb(id)),
  resizeWidget: (size) => ipcRenderer.send('widget:resize', size),
  getWidgetSize: () => ipcRenderer.invoke('widget:get-size'),
  getWidgetPos: () => ipcRenderer.invoke('widget:get-pos'),
  getWidgetBounds: () => ipcRenderer.invoke('widget:get-bounds'),
  setWidgetBounds: (b) => ipcRenderer.send('widget:set-bounds', b),

  // 이벤트 기록 (트레이에서 켤 때만 동작)
  debugLog: (source, message) => ipcRenderer.send('debug:log', { source, message }),
  onDebugMode: (cb) => ipcRenderer.on('debug:mode', (_e, on) => cb(on)),
  moveWidget: (pos) => ipcRenderer.send('widget:move', pos),

  // 오버레이
  getOverlayBg: (displayId) => ipcRenderer.invoke('overlay:get-bg', displayId),
  getBreakPayload: () => ipcRenderer.invoke('overlay:get-payload'),
  // 휴식 창은 미리 만들어 두고 숨겨 놓는다 — 시작 신호를 받으면 그때 그린다
  onBreakBegin: (cb) => ipcRenderer.on('overlay:begin', (_e, p) => cb(p)),
  snooze: () => ipcRenderer.send('overlay:snooze'),
  skip: () => ipcRenderer.send('overlay:skip'),
  finish: () => ipcRenderer.send('overlay:done'),

  // 설정
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setApp: (patch) => ipcRenderer.send('settings:set-app', patch),
  setReminder: (id, patch) => ipcRenderer.send('settings:set-reminder', { id, patch }),
  customAdd: (def) => ipcRenderer.invoke('settings:custom-add', def),
  customUpdate: (id, patch) => ipcRenderer.invoke('settings:custom-update', { id, patch }),
  customRemove: (id) => ipcRenderer.invoke('settings:custom-remove', id),
  closeSettings: () => ipcRenderer.send('settings:close'),

  // 캘린더
  calAdd: (name, url) => ipcRenderer.invoke('cal:add', { name, url }),
  calUpdate: (id, patch) => ipcRenderer.invoke('cal:update', { id, patch }),
  calRemove: (id) => ipcRenderer.invoke('cal:remove', id),
  calRefresh: () => ipcRenderer.invoke('cal:refresh'),
  calTest: (url) => ipcRenderer.invoke('cal:test', url),
  calClipboard: () => ipcRenderer.invoke('cal:clipboard'),
  calMonth: (year, month) => ipcRenderer.invoke('cal:month', { year, month }),
  openCalendar: () => ipcRenderer.send('cal:open'),
  calPanel: (info) => ipcRenderer.send('cal:panel', info),
  calOpenEvent: (ev) => ipcRenderer.invoke('cal:open-event', ev),
  calNewEvent: (range) => ipcRenderer.invoke('cal:new-event', range),
  onCalShow: (cb) => ipcRenderer.on('cal:show', () => cb()),
  onMailShow: (cb) => ipcRenderer.on('mail:show', () => cb()),

  // 주식 — 별도 창. 관심 종목은 이 앱이 직접 들고 있다.
  stocksOpen: () => ipcRenderer.send('stocks:open'),
  stocksClose: () => ipcRenderer.send('stocks:close'),
  stocksRefresh: () => ipcRenderer.invoke('stocks:refresh'),
  stocksSearch: (q) => ipcRenderer.invoke('stocks:search', q),
  stocksAdd: (input) => ipcRenderer.invoke('stocks:add', input),
  stocksRemove: (ticker) => ipcRenderer.invoke('stocks:remove', ticker),
  stocksSetApp: (patch) => ipcRenderer.invoke('stocks:set-app', patch),
  stocksImport: (root) => ipcRenderer.invoke('stocks:import', root),
  onStocksData: (cb) => ipcRenderer.on('stocks:data', (_e, b) => cb(b)),
  stocksBounds: () => ipcRenderer.invoke('stocks:bounds'),
  stocksSetBounds: (b) => ipcRenderer.send('stocks:set-bounds', b),
  stocksMove: (p) => ipcRenderer.send('stocks:move', p),
  onCalChanged: (cb) => ipcRenderer.on('cal:changed', () => cb()),
  calOpenHelp: (which) => ipcRenderer.invoke('cal:open-help', which),
  calPickFile: () => ipcRenderer.invoke('cal:pick-file'),

  // 메일 (비밀번호는 메인에서만 다룬다)
  mailGet: () => ipcRenderer.invoke('mail:get'),
  mailTest: (acc) => ipcRenderer.invoke('mail:test', acc),
  mailAdd: (acc) => ipcRenderer.invoke('mail:add', acc),
  mailUpdate: (id, patch) => ipcRenderer.invoke('mail:update', { id, patch }),
  mailRemove: (id) => ipcRenderer.invoke('mail:remove', id),
  mailRefresh: () => ipcRenderer.invoke('mail:refresh'),
  mailMarkRead: (opts) => ipcRenderer.invoke('mail:mark-read', opts || {}),
  mailSmtpTest: (acc) => ipcRenderer.invoke('mail:smtp-test', acc),
  composeOpen: (opts) => ipcRenderer.invoke('compose:open', opts || {}),
  composeData: () => ipcRenderer.invoke('compose:data'),
  composeSend: (msg) => ipcRenderer.invoke('compose:send', msg),
  composeAttach: () => ipcRenderer.invoke('compose:attach'),
  composePickImage: () => ipcRenderer.invoke('compose:pick-image'),
  mailRowMenu: (m) => ipcRenderer.invoke('mail:row-menu', m),
  mailSent: () => ipcRenderer.invoke('mail:sent'),
  mailMore: (folder) => ipcRenderer.invoke('mail:more', folder || 'in'),
  mailRules: () => ipcRenderer.invoke('mail:rules'),
  mailRuleAdd: (r) => ipcRenderer.invoke('mail:rule-add', r),
  mailRuleUpdate: (id, patch) => ipcRenderer.invoke('mail:rule-update', { id, patch }),
  mailRuleRemove: (id) => ipcRenderer.invoke('mail:rule-remove', id),
  mailContacts: () => ipcRenderer.invoke('mail:contacts'),
  mailContactSave: (c) => ipcRenderer.invoke('mail:contact-save', c),
  mailContactRemove: (a) => ipcRenderer.invoke('mail:contact-remove', a),
  mailContactsImport: () => ipcRenderer.invoke('mail:contacts-import'),
  mailContactsExport: () => ipcRenderer.invoke('mail:contacts-export'),
  composeClose: () => ipcRenderer.send('compose:close'),
  composeDraftSave: (d) => ipcRenderer.send('compose:draft-save', d),
  composeDraftClear: () => ipcRenderer.send('compose:draft-clear'),
  composeAsk: (kind) => ipcRenderer.invoke('compose:ask', kind),
  composeAcceptReplace: (p) => ipcRenderer.send('compose:accept-replace', p),
  composeSetAccount: (id) => ipcRenderer.send('compose:set-account', id),
  onComposeReplace: (cb) => ipcRenderer.on('compose:replace', (_e, p) => cb(p)),
  composeBounds: () => ipcRenderer.invoke('compose:bounds'),
  composeSetBounds: (b) => ipcRenderer.send('compose:set-bounds', b),
  composeMove: (p) => ipcRenderer.send('compose:move', p),
  mailBackupStatus: () => ipcRenderer.invoke('mail:backup-status'),
  mailBackupPick: () => ipcRenderer.invoke('mail:backup-pick'),
  mailBackupStart: () => ipcRenderer.invoke('mail:backup-start'),
  mailBackupStop: () => ipcRenderer.send('mail:backup-stop'),
  mailBackupOpen: () => ipcRenderer.send('mail:backup-open'),
  mailOpen: (msg) => ipcRenderer.invoke('mail:open', msg),
  mailViewData: () => ipcRenderer.invoke('mail:view-data'),
  mailViewClose: () => ipcRenderer.send('mail:view-close'),
  // 물어보는 창 · 오른쪽 클릭 메뉴 (앱 마감으로 그린다)
  pickMenu: (items) => ipcRenderer.invoke('ui:menu', items),
  popupData: () => ipcRenderer.invoke('popup:data'),
  popupSize: (s) => ipcRenderer.send('popup:size', s),
  popupPick: (v) => ipcRenderer.send('popup:pick', v),

  mailCopy: () => ipcRenderer.invoke('mail:copy'),
  mailTrash: () => ipcRenderer.invoke('mail:trash'),
  mailSaveAttachment: (i) => ipcRenderer.invoke('mail:save-attachment', i),
  mailPreviewAttachment: (i) => ipcRenderer.invoke('mail:preview-attachment', i),
  mailReveal: (p) => ipcRenderer.send('mail:reveal', p),
  mailViewBounds: () => ipcRenderer.invoke('mailview:bounds'),
  mailViewSetBounds: (b) => ipcRenderer.send('mailview:set-bounds', b),
  mailViewMove: (pos) => ipcRenderer.send('mailview:move', pos),
  openUrl: (url) => ipcRenderer.invoke('app:open-url', url),

  // 자동 실행 (OS 상태를 그대로 읽고 쓴다)
  autoLaunchGet: () => ipcRenderer.invoke('autolaunch:get'),
  autoLaunchSet: (on) => ipcRenderer.invoke('autolaunch:set', on),

  // 기록
  statsGet: () => ipcRenderer.invoke('stats:get'),
  statsResetToday: () => ipcRenderer.invoke('stats:reset-today'),
  statsResetAll: () => ipcRenderer.invoke('stats:reset-all'),

  // 업데이트
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateState: () => ipcRenderer.invoke('update:state'),
  updateInstall: () => ipcRenderer.send('update:install'),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (_e, s) => cb(s))
});
